### ISSUE TITLE
extention issue

### ISSUE THREAD

**Issue by sleepy1235** [ChrisEric1/ChrisEric1.github.io#25]
the extention does not work to add... therefore i cant login

**Comment by CE1CECL** [comment]
> the extention does not work to add... therefore i cant login

What browser? Chrome? If its chrome, I have to look into it, it probably relates to the manifest v3 only issue, and my extension is manifest v2.

**Comment by CE1CECL** [comment]
![Screen Shot 2024-01-11 at 8 29 36 AM](https://github.com/ChrisEric1/ChrisEric1.GitHub.io/assets/52040854/75699422-79de-4998-83b7-7dc32114b55f)
I cannot confirm this issue on Chromium for OS X, so therefore without it being enforced by a browser, I can't fix this issue until then. Not sure if I should keep this open or not because one of the errors in chrome://extensions said "will be removed in 2024". I'll decide on closing or not on 1/24/2024 unless there is a reply by anyone sooner than that date.

**Comment by CE1CECL** [comment]
Completely forgot about the last comment, this will be closed until it really affects people, once it does get ended, because it may (or may not) extend again.
